<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_testimonials"
 *
 * Auto generated by Extension Builder 2014-02-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Pxa TYPO3 Form Recaptcha',
	'description' => 'Allow to add recaptcha to TYPO3 form',
	'category' => 'plugin',
	'author' => 'Andriy',
	'author_email' => 'andriy@pixelant.se',
	'author_company' => 'Pixelant',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
            'form' => ''
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>